### ISSUE TITLE
Refactor SlippiGame.h and .cpp

### ISSUE THREAD

**Issue by r2dliu** [r2dliu/dolphin#1]
C++17 supports std::byte, which should be used wherever possible for clarity and safety.

std::filesystem::path and std::filesystem::u8path should be used instead of strings and wstrings.
Some branching logic will be required because std::filesystem::path does not support utf8 characters by default until c++20.

**Comment by r2dliu** [comment]
Work around to solve branching in fileutils
```
#ifdef HAS_STD_FILESYSTEM
// This is a replacement for path::u8path, which is deprecated starting with C++20.
std::filesystem::path StringToPath(std::string_view path)
{
#ifdef _MSC_VER
  return std::filesystem::path(UTF8ToUTF16(path));
#else
  return std::filesystem::path(path);
#endif
}
```

**Comment by JosJuice** [comment]
> Some branching logic will be required because std::filesystem::path does not support utf8 characters by default until c++20.

Not quite. UTF-8 support works perfectly in C++17, but C++20 deprecated any way of using UTF-8 with std::filesystem::path that doesn't involve std::u8string, and using std::u8string is annoying when you're using std::string for UTF-8 strings everywhere else, not to mention when you're trying to still support C++17 compilers.

See also my comment about std::filesystem at https://github.com/r2dliu/dolphin/issues/2#issuecomment-654096791.
