### ISSUE TITLE
Refactor FileUtils and File (.h, .cpp)

### ISSUE THREAD

**Issue by r2dliu** [r2dliu/dolphin#2]
Many of these can be updated to have less branching code for different operating systems. (std::filesystem)

File.h/.cpp is okay depending on use of those functions. Need reeval after implementing rest of system where it's actually used.

**Comment by JosJuice** [comment]
The ecosystem support for std::filesystem on non-Windows isn't quite there yet. To avoid unnecessarily breaking older gcc/clang and potentially all currently released NDK versions for Android (I heard they were going to support it in the next release but don't know if that's out yet), I'd suggest keeping support for a non-std::filesystem path on all OSes other than Windows. Mainline will switch over to using only std::filesystem once the ecosystem is ready for it.
